name: Build Test Client

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Build test client
      shell: cmd
      run: |
        cl.exe full_test.cpp /EHsc /Fe:full_test.exe /O2 /link ntdll.lib

    - name: Upload test client
      uses: actions/upload-artifact@v4
      with:
        name: full_test
        path: full_test.exe
        if-no-files-found: error
