name: Build Test Driver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build test driver
      shell: cmd
      run: |
        msbuild test_driver.vcxproj ^
          /p:Configuration=${{ matrix.configuration }} ^
          /p:Platform=${{ matrix.platform }} ^
          /p:SignMode=Off

    - name: Upload test driver
      uses: actions/upload-artifact@v4
      with:
        name: TestDriver
        path: x64\Release\test_driver.sys
        if-no-files-found: error
